PROJECT_TYPE_NAMES = [
    "type1",
    "type2",
    "type3",
    "type4",
    "typ5",
]

[GOOGLE_DRIVE_TOKEN]
enable = false
credential_path = ""

[GITHUB_TOKEN]
enable = false
variable_name = ""

[DB]
DB_FILE_NAME = "db.pickle"

[ROOT_DIRECTORY]
main_dir = ""

[SUB_DIRECTORY]
